/**
 * Esmâ-i Hüsnâ — 99 ismin anlamları (TR/EN/AR).
 * Anlamlar, yaygın kabul gören klasik glossların kendi cümlelerimizle ifadesidir.
 * Anahtar (key) olarak sade bir Latin harf slug kullanılır.
 */

export interface EsmaMeaning {
  arabic: string;
  transliteration: string; // TR okunuş, "el-" / "er-" / "eş-" / "es-" / "ez-" / "et-" dahil
  tr: string;
  en: string;
  ar: string;
}

export const ESMA_MEANINGS: Record<string, EsmaMeaning> = {
  allah: { arabic: "الله", transliteration: "Allâh", tr: "Zât-ı ilâhînin has ismi, bütün güzel isimleri kendinde toplayan", en: "The proper name of God, encompassing all divine attributes", ar: "الاسم الخاص بالذات الإلهية" },
  rahman: { arabic: "الرحمن", transliteration: "er-Rahmân", tr: "Tüm yaratılmışlara merhamet eden", en: "Merciful to all creation", ar: "الراحم لجميع المخلوقات" },
  rahim: { arabic: "الرحيم", transliteration: "er-Rahîm", tr: "Özellikle müminlere merhamet eden", en: "Especially merciful to believers", ar: "الراحم بالمؤمنين خاصة" },
  melik: { arabic: "الملك", transliteration: "el-Melik", tr: "Mülkün ve kâinatın gerçek sahibi", en: "The true owner of all dominion", ar: "المالك الحقيقي للملك كله" },
  kuddus: { arabic: "القدوس", transliteration: "el-Kuddûs", tr: "Her türlü eksiklik ve kusurdan uzak", en: "Free from all imperfection", ar: "المنزه عن كل نقص" },
  selam: { arabic: "السلام", transliteration: "es-Selâm", tr: "Her türlü afetten esenlik veren", en: "Source of peace and safety", ar: "مصدر السلامة من كل آفة" },
  mumin: { arabic: "المؤمن", transliteration: "el-Mü'min", tr: "Güven ve emniyet veren", en: "Giver of security and trust", ar: "الذي يهب الأمان" },
  muheymin: { arabic: "المهيمن", transliteration: "el-Müheymin", tr: "Her şeyi gözetip koruyan", en: "The Watchful Protector over all", ar: "الرقيب الحافظ على كل شيء" },
  aziz: { arabic: "العزيز", transliteration: "el-Azîz", tr: "Karşı durulamaz güç ve şeref sahibi", en: "Possessor of irresistible might and honor", ar: "صاحب العزة التي لا تُقهر" },
  cebbar: { arabic: "الجبار", transliteration: "el-Cebbâr", tr: "İradesini dilediği gibi yürüten, telafi edici", en: "The Compeller who restores and mends", ar: "الذي يُصلح ويُجبر الكسر" },
  mutekebbir: { arabic: "المتكبر", transliteration: "el-Mütekebbir", tr: "Büyüklüğü her şeyin üstünde olan", en: "The Supremely Great, above all", ar: "العظيم فوق كل شيء" },
  halik: { arabic: "الخالق", transliteration: "el-Hâlık", tr: "Yaratan", en: "The Creator", ar: "الخالق" },
  bari: { arabic: "البارئ", transliteration: "el-Bâri'", tr: "Kusursuz, ölçülü bir şekilde var eden", en: "The Flawless Maker", ar: "الذي يُبدع الخلق بلا عيب" },
  musavvir: { arabic: "المصور", transliteration: "el-Musavvir", tr: "Her varlığa kendine özgü şekil veren", en: "The Shaper, giver of unique form", ar: "الذي يعطي كل شيء صورته الخاصة" },
  gaffar: { arabic: "الغفار", transliteration: "el-Gaffâr", tr: "Günahları tekrar tekrar bağışlayan", en: "The Ever-Forgiving, again and again", ar: "الذي يغفر الذنوب مرارًا" },
  kahhar: { arabic: "القهار", transliteration: "el-Kahhâr", tr: "Her şeye galip gelen", en: "The All-Dominant, ever victorious", ar: "الغالب على كل شيء" },
  vehhab: { arabic: "الوهاب", transliteration: "el-Vehhâb", tr: "Karşılıksız, bol bol bağışta bulunan", en: "The Bestower of gifts without measure", ar: "الذي يهب بلا حساب" },
  rezzak: { arabic: "الرزاق", transliteration: "er-Rezzâk", tr: "Bütün canlıların rızkını veren", en: "Provider of sustenance to all", ar: "الذي يرزق جميع المخلوقات" },
  fettah: { arabic: "الفتاح", transliteration: "el-Fettâh", tr: "Hayır kapılarını açan, zorlukları çözen", en: "The Opener of good and solver of difficulty", ar: "الذي يفتح أبواب الخير ويحل العسير" },
  alim: { arabic: "العليم", transliteration: "el-Alîm", tr: "Her şeyi, gizli açık, en ince ayrıntısıyla bilen", en: "The All-Knowing, of seen and unseen alike", ar: "العالم بكل شيء ظاهرًا وباطنًا" },
  kabiz: { arabic: "القابض", transliteration: "el-Kâbız", tr: "Daraltan, sıkan", en: "The Constrictor, who withholds", ar: "الذي يقبض ويضيق" },
  basit: { arabic: "الباسط", transliteration: "el-Bâsıt", tr: "Genişleten, bolluk veren", en: "The Expander, giver of abundance", ar: "الذي يبسط ويوسع" },
  hafid: { arabic: "الخافض", transliteration: "el-Hâfıd", tr: "Alçaltan, değersiz kılan", en: "The Abaser, who lowers", ar: "الذي يخفض من يشاء" },
  rafi: { arabic: "الرافع", transliteration: "er-Râfi'", tr: "Yükselten, derece veren", en: "The Exalter, who raises in rank", ar: "الذي يرفع من يشاء" },
  muizz: { arabic: "المعز", transliteration: "el-Muizz", tr: "İzzet ve şeref veren", en: "The Honorer, giver of dignity", ar: "الذي يعز من يشاء" },
  muzill: { arabic: "المذل", transliteration: "el-Müzill", tr: "Alçaltan, zillete düşüren", en: "The Humiliator of whom He wills", ar: "الذي يذل من يشاء" },
  semi: { arabic: "السميع", transliteration: "es-Semî'", tr: "Her şeyi işiten", en: "The All-Hearing", ar: "السميع لكل شيء" },
  basir: { arabic: "البصير", transliteration: "el-Basîr", tr: "Her şeyi gören", en: "The All-Seeing", ar: "البصير بكل شيء" },
  hakem: { arabic: "الحكم", transliteration: "el-Hakem", tr: "Adaletle hükmeden", en: "The Judge, who rules with justice", ar: "الحاكم بالعدل" },
  adl: { arabic: "العدل", transliteration: "el-Adl", tr: "Mutlak adil olan", en: "The Utterly Just", ar: "العادل المطلق" },
  latif: { arabic: "اللطيف", transliteration: "el-Latîf", tr: "İnceliklere vakıf, lütufkâr", en: "The Subtly Gracious, aware of every detail", ar: "اللطيف العالم بدقائق الأمور" },
  habir: { arabic: "الخبير", transliteration: "el-Habîr", tr: "Her şeyden haberdar", en: "The All-Aware", ar: "الخبير بكل شيء" },
  halim: { arabic: "الحليم", transliteration: "el-Halîm", tr: "Hemen cezalandırmayan, yumuşak davranan", en: "The Forbearing, slow to punish", ar: "الحليم الذي لا يعجل بالعقاب" },
  azim: { arabic: "العظيم", transliteration: "el-Azîm", tr: "Pek büyük, ululuk sahibi", en: "The Magnificent, possessor of greatness", ar: "العظيم في صفاته" },
  gafur: { arabic: "الغفور", transliteration: "el-Gafûr", tr: "Çok bağışlayan, günahları örten", en: "The Much-Forgiving, who veils sins", ar: "الغفور الذي يستر الذنوب" },
  sekur: { arabic: "الشكور", transliteration: "eş-Şekûr", tr: "Az amele büyük mükâfat veren", en: "The Most Appreciative, rewarding little with much", ar: "الذي يجزي على القليل بالكثير" },
  aliyy: { arabic: "العلي", transliteration: "el-Aliyy", tr: "Çok yüce", en: "The Most High", ar: "العلي الأعلى" },
  kebir: { arabic: "الكبير", transliteration: "el-Kebîr", tr: "Büyüklükte eşi olmayan", en: "The Greatest, beyond comparison", ar: "الكبير الذي لا مثيل له" },
  hafiz: { arabic: "الحفيظ", transliteration: "el-Hafîz", tr: "Koruyan, gözeten", en: "The Preserver, who watches over", ar: "الحفيظ الراعي" },
  mukit: { arabic: "المقيت", transliteration: "el-Mukît", tr: "Rızık ve gücü veren, gözetip besleyen", en: "The Sustainer, who nourishes and empowers", ar: "الذي يقيت ويغذي" },
  hasib: { arabic: "الحسيب", transliteration: "el-Hasîb", tr: "Hesabı en iyi gören, yeten", en: "The Reckoner, sufficient unto Himself", ar: "الحسيب الكافي" },
  celil: { arabic: "الجليل", transliteration: "el-Celîl", tr: "Azamet ve yücelik sahibi", en: "Possessor of majesty", ar: "صاحب الجلال" },
  kerim: { arabic: "الكريم", transliteration: "el-Kerîm", tr: "Çok cömert, karşılıksız ikram eden", en: "The Most Generous, who gives without expecting return", ar: "الكريم الكثير العطاء" },
  rakib: { arabic: "الرقيب", transliteration: "er-Rakîb", tr: "Her şeyi an be an gözetip kontrol eden", en: "The Ever-Watchful Observer", ar: "الرقيب على كل شيء" },
  mucib: { arabic: "المجيب", transliteration: "el-Mücîb", tr: "Duaları kabul eden", en: "The Responder to prayers", ar: "المجيب للدعاء" },
  vasi: { arabic: "الواسع", transliteration: "el-Vâsi'", tr: "İlmi, rahmeti her şeyi kuşatan", en: "The All-Encompassing, in knowledge and mercy", ar: "الواسع العلم والرحمة" },
  hakim: { arabic: "الحكيم", transliteration: "el-Hakîm", tr: "Her işi hikmetle yapan", en: "The All-Wise, acting with perfect wisdom", ar: "الحكيم في كل أفعاله" },
  vedud: { arabic: "الودود", transliteration: "el-Vedûd", tr: "Çok seven ve sevilen", en: "The Most Loving and Most Beloved", ar: "الودود الكثير المحبة" },
  mecid: { arabic: "المجيد", transliteration: "el-Mecîd", tr: "Şanı, şerefi çok yüce", en: "The Glorious, of supreme honor", ar: "المجيد الرفيع الشأن" },
  bais: { arabic: "الباعث", transliteration: "el-Bâis", tr: "Ölümden sonra yeniden dirilten", en: "The Resurrector, who raises after death", ar: "الباعث بعد الموت" },
  sehid: { arabic: "الشهيد", transliteration: "eş-Şehîd", tr: "Her an her yerde hazır, şahit olan", en: "The Witness, present everywhere", ar: "الشاهد على كل شيء" },
  hak: { arabic: "الحق", transliteration: "el-Hak", tr: "Varlığı kesin ve değişmez gerçek", en: "The Absolute Truth, unchanging reality", ar: "الحق الثابت" },
  vekil: { arabic: "الوكيل", transliteration: "el-Vekîl", tr: "İşleri yoluna koyan, güvenilen vekil", en: "The Trustee, who manages affairs", ar: "الوكيل الذي يتولى الأمور" },
  kavi: { arabic: "القوي", transliteration: "el-Kavî", tr: "Sonsuz güç sahibi", en: "The All-Strong", ar: "القوي المطلق" },
  metin: { arabic: "المتين", transliteration: "el-Metîn", tr: "Çok sağlam, sarsılmaz", en: "The Firm, unshakeable", ar: "المتين الثابت" },
  veli: { arabic: "الولي", transliteration: "el-Velî", tr: "Müminlerin dostu, yardımcısı", en: "The Protecting Friend of believers", ar: "ولي المؤمنين" },
  hamid: { arabic: "الحميد", transliteration: "el-Hamîd", tr: "Övgüye en layık olan", en: "The Most Praiseworthy", ar: "الحميد المستحق للحمد" },
  muhsi: { arabic: "المحصي", transliteration: "el-Muhsî", tr: "Her şeyin sayısını bilen", en: "The Reckoner of all things", ar: "المحصي لكل شيء" },
  mubdi: { arabic: "المبدئ", transliteration: "el-Mübdi'", tr: "Her şeyi ilk olarak yoktan yaratan", en: "The Originator, first creator", ar: "المبدئ للخلق" },
  muid: { arabic: "المعيد", transliteration: "el-Muîd", tr: "Yarattığını tekrar yaratan, dirilten", en: "The Restorer, who recreates", ar: "المعيد للخلق" },
  muhyi: { arabic: "المحيي", transliteration: "el-Muhyî", tr: "Hayat veren", en: "The Giver of Life", ar: "المحيي" },
  mumit: { arabic: "المميت", transliteration: "el-Mümît", tr: "Öldüren", en: "The Bringer of Death", ar: "المميت" },
  hayy: { arabic: "الحي", transliteration: "el-Hayy", tr: "Diri, hayatın asıl sahibi", en: "The Ever-Living", ar: "الحي الباقي" },
  kayyum: { arabic: "القيوم", transliteration: "el-Kayyûm", tr: "Kendi kendine var olan, her şeyi ayakta tutan", en: "The Self-Subsisting Sustainer of all", ar: "القيوم القائم بنفسه" },
  vacid: { arabic: "الواجد", transliteration: "el-Vâcid", tr: "Hiçbir şeye muhtaç olmayan, istediğini bulan", en: "The Self-Sufficient Finder", ar: "الواجد الغني عن كل شيء" },
  macid: { arabic: "الماجد", transliteration: "el-Mâcid", tr: "Şanı ve kerem bol olan", en: "The Noble, abundant in honor", ar: "الماجد الكريم" },
  vahid: { arabic: "الواحد", transliteration: "el-Vâhid", tr: "Bir, eşi benzeri olmayan", en: "The One, without equal", ar: "الواحد الذي لا نظير له" },
  ehad: { arabic: "الأحد", transliteration: "el-Ehad", tr: "Tek, parçalanmaz bütün", en: "The Indivisible One", ar: "الأحد الذي لا ينقسم" },
  samed: { arabic: "الصمد", transliteration: "es-Samed", tr: "Herkesin muhtaç olduğu, kendisi muhtaç olmayan", en: "The Self-Sufficient, on whom all depend", ar: "الصمد الذي يُحتاج إليه ولا يحتاج" },
  kadir: { arabic: "القادر", transliteration: "el-Kâdir", tr: "Her şeye gücü yeten", en: "The All-Capable", ar: "القادر على كل شيء" },
  muktedir: { arabic: "المقتدر", transliteration: "el-Muktedir", tr: "Kudretiyle dilediği gibi tasarruf eden", en: "The All-Powerful, who exercises full might", ar: "المقتدر صاحب القدرة الكاملة" },
  mukaddim: { arabic: "المقدم", transliteration: "el-Mukaddim", tr: "Dilediğini öne alan, ileri geçiren", en: "The Expediter, who brings forward", ar: "المقدم لما يشاء" },
  muahhir: { arabic: "المؤخر", transliteration: "el-Muahhir", tr: "Dilediğini geriye bırakan", en: "The Delayer, who postpones", ar: "المؤخر لما يشاء" },
  evvel: { arabic: "الأول", transliteration: "el-Evvel", tr: "Varlığının başlangıcı olmayan, ilk", en: "The First, without beginning", ar: "الأول الذي لا بداية له" },
  ahir: { arabic: "الآخر", transliteration: "el-Âhir", tr: "Varlığının sonu olmayan, son", en: "The Last, without end", ar: "الآخر الذي لا نهاية له" },
  zahir: { arabic: "الظاهر", transliteration: "ez-Zâhir", tr: "Varlığı apaçık görülen", en: "The Manifest, evident through His signs", ar: "الظاهر بآياته" },
  batin: { arabic: "الباطن", transliteration: "el-Bâtın", tr: "Zâtı gözle görülmeyen, gizli", en: "The Hidden, beyond perception", ar: "الباطن الذي لا يُدرك بالحس" },
  vali: { arabic: "الوالي", transliteration: "el-Vâlî", tr: "Bütün işleri yöneten", en: "The Governor of all affairs", ar: "الوالي المتولي لكل الأمور" },
  muteal: { arabic: "المتعالي", transliteration: "el-Müteâl", tr: "Akıl ve hayalin erişemeyeceği kadar yüce", en: "The Most Exalted, beyond imagination", ar: "المتعالي عن الإدراك" },
  birr: { arabic: "البر", transliteration: "el-Birr", tr: "İyilik ve ihsanı bol olan", en: "The Source of Goodness", ar: "البر الكثير الإحسان" },
  tevvab: { arabic: "التواب", transliteration: "et-Tevvâb", tr: "Tevbeleri çok kabul eden", en: "The Ever-Accepting of repentance", ar: "التواب القابل للتوبة" },
  muntakim: { arabic: "المنتقم", transliteration: "el-Müntakim", tr: "Haksızlık edenlerin hakkını adaletle alan", en: "The Avenger of wrongdoing, with justice", ar: "المنتقم بالعدل" },
  afuvv: { arabic: "العفو", transliteration: "el-Afüvv", tr: "Günahları silip affeden", en: "The Pardoner, who erases sin", ar: "العفو الذي يمحو الذنوب" },
  rauf: { arabic: "الرؤوف", transliteration: "er-Raûf", tr: "Çok şefkatli", en: "The Most Compassionate", ar: "الرؤوف الرحيم" },
  malikulmulk: { arabic: "مالك الملك", transliteration: "Mâlikü'l-Mülk", tr: "Mülkün gerçek ve tek sahibi", en: "The Sovereign Owner of all dominion", ar: "مالك الملك كله" },
  zulcelal: { arabic: "ذو الجلال والإكرام", transliteration: "Zü'l-Celâli ve'l-İkrâm", tr: "Azamet ve ikram sahibi", en: "Lord of Majesty and Generosity", ar: "ذو الجلال والإكرام" },
  muksit: { arabic: "المقسط", transliteration: "el-Muksıt", tr: "Adaleti tam uygulayan", en: "The Equitable, who applies justice fully", ar: "المقسط العادل" },
  cami: { arabic: "الجامع", transliteration: "el-Câmi'", tr: "Dilediğini bir araya toplayan", en: "The Gatherer, who unites as He wills", ar: "الجامع لما يشاء" },
  gani: { arabic: "الغني", transliteration: "el-Ganî", tr: "Hiçbir şeye muhtaç olmayan", en: "The Self-Sufficient, needing nothing", ar: "الغني عن كل شيء" },
  mugni: { arabic: "المغني", transliteration: "el-Mugnî", tr: "Dilediğini zenginleştiren", en: "The Enricher, who grants sufficiency", ar: "المغني لمن يشاء" },
  mani: { arabic: "المانع", transliteration: "el-Mâni'", tr: "İstemediği şeyin olmasına izin vermeyen", en: "The Preventer, who withholds what He wills", ar: "المانع لما لا يريد" },
  darr: { arabic: "الضار", transliteration: "ed-Dârr", tr: "Hikmeti gereği zarar verebilen", en: "The One who, by His wisdom, can bring harm", ar: "الضار بحكمته" },
  nafi: { arabic: "النافع", transliteration: "en-Nâfi'", tr: "Fayda veren", en: "The Beneficial", ar: "النافع" },
  nur: { arabic: "النور", transliteration: "en-Nûr", tr: "Nur, aydınlatan", en: "The Light, illuminator", ar: "النور المنير" },
  hadi: { arabic: "الهادي", transliteration: "el-Hâdî", tr: "Doğru yola ileten", en: "The Guide to the right path", ar: "الهادي إلى الصراط" },
  bedi: { arabic: "البديع", transliteration: "el-Bedî'", tr: "Eşsiz, örneksiz yaratan", en: "The Originator of the unprecedented", ar: "البديع الخلق" },
  baki: { arabic: "الباقي", transliteration: "el-Bâkî", tr: "Varlığı sonsuz, ebedî olan", en: "The Everlasting", ar: "الباقي الأبدي" },
  varis: { arabic: "الوارث", transliteration: "el-Vâris", tr: "Her şeyin gerçek mirasçısı", en: "The True Inheritor of all", ar: "الوارث لكل شيء" },
  resid: { arabic: "الرشيد", transliteration: "er-Reşîd", tr: "Doğru yolu gösteren", en: "The Guide to right conduct", ar: "الرشيد الهادي" },
  sabur: { arabic: "الصبور", transliteration: "es-Sabûr", tr: "Cezalandırmada acele etmeyen, çok sabırlı", en: "The Most Patient, never hasty to punish", ar: "الصبور الذي لا يعجل" },
  // Kaynaktaki tabloda "el-Müşterî" olarak geçen, fakat 99 ismin standart listesinde karşılığı
  // bulunmayan (Müşterî = Jüpiter gezegeninin adı) şüpheli bir girdi. Düzeltmeye çalışmadan,
  // kaynakta nasılsa öyle bırakıldı.
  musteri_suspicious: { arabic: "المشتري", transliteration: "el-Müşterî (?)", tr: "Kaynakta şüpheli bir girdi — standart 99 isim listesinde karşılığı bulunamadı", en: "A questionable entry in the source — no match found in the standard list of 99 names", ar: "مدخل مشكوك فيه في المصدر — لا يوجد له مقابل في القائمة المعتادة" },
};
